### ISSUE TITLE
Seems no register for Taiga

### ISSUE THREAD

**Issue by Caishangqi** [Peatral/EmbersConstruct#4] opened 2020-06-15 21:17 UTC
Hi, I add embers construct, petwer and Taiga, but it only register petwer and tinkers construct material and melting, there are no registration of Taiga material.
![image](https://user-images.githubusercontent.com/39553613/84706832-87276700-af12-11ea-9cb3-ae5e70a6e31d.png)
embers Construct register Petwer material
![image](https://user-images.githubusercontent.com/39553613/84706958-b938c900-af12-11ea-8500-3b9cb489822a.png)
It seems have no registration for Taiga material
![image](https://user-images.githubusercontent.com/39553613/84707064-e2595980-af12-11ea-8786-1d94a0dd9862.png)
![image](https://user-images.githubusercontent.com/39553613/84707089-edac8500-af12-11ea-9d62-0911717207bd.png)

**Comment by Peatral** [comment] 2020-06-15 21:27
If Taiga is initialized after Embers Construct, the materials get added after Embers Construct add the recipes. Although that may not be the causd, it's pretty likely and I will check it tomorrow (it's currently 11:25pm in Germany). Stuff like that should be fixed by initializing it after Taiga. That is the general rule of thumb.

**Comment by Caishangqi** [comment] 2020-06-15 21:31
Thanks :3

**Comment by Peatral** [comment] 2020-06-16 16:02
I looked into it and currently it seems like the stuff I mentioned weren't the problem. The problem is that Taiga does not register the fluids for the materials. That is kinda silly and there are a few ways how I could fix that. I think the most logical and reasonable is that I could check if a material has no fluid but if there's a fluid where the identifiers match I add the recipe (and maybe register the fluid for the material). Because this seems a bit risky and could lead to unintentional matches, I would make this configurable. But because on the other hand the ore dictionary groups ores/fluids etc. with the same name, it would make sense to have this feature turned on by default because unintentional matches should be really rare.

**Comment by Peatral** [comment] 2020-06-16 16:18
The problem wasn't the one I mentioned before. The actual problem was that the name taiga registered the fluids under had a "_fluid" suffix and therefore didn't match the material identifiers. I will fix it and get in touch again when I'm finished.

**Comment by Peatral** [comment] 2020-06-16 17:29
1. Alloying already worked because the fluids just get copied over (as long as the tinkers smeltery is enabled of course)
2. Stamping does now work again
3. Melting does still not work due to an unidentified problem

**Comment by Peatral** [comment] 2020-06-16 18:13
Okay, it's pretty weird but somehow the line that actually registers the final recipe was missing. I'm now wondering how other melting recipes still work without it but I have everything fixed now.

- Fixed Melting Recipes not registering
- When dealing with fluids, "fluid" pre- and suffixes are now also checked to provide better support 

Fixed with f8af19134f26f59f4ddc64770a3314e3f1a1664a

**Closed** 2020-06-16 18:13 UTC

**Comment by Caishangqi** [comment] 2020-06-16 23:52
> Okay, it's pretty weird but somehow the line that actually registers the final recipe was missing. I'm now wondering how other melting recipes still work without it but I have everything fixed now.
> 
> * Fixed Melting Recipes not registering
> * When dealing with fluids, "fluid" pre- and suffixes are now also checked to provide better support
> 
> Fixed with [f8af191](https://github.com/Peatral/EmbersConstruct/commit/f8af19134f26f59f4ddc64770a3314e3f1a1664a)

thanks a lot, really help me :3
