### ISSUE TITLE
There are no stamp recipe of ingot for Tagia and Petwer material

### ISSUE THREAD

**Issue by Caishangqi** [Peatral/EmbersConstruct#6] opened 2020-06-19 00:09 UTC
Hi, I found that there are no stamp recipe of ingot for Tagia and Petwer material
### The Taiga Material(ingot)
![image](https://user-images.githubusercontent.com/39553613/85083115-a11cb000-b185-11ea-947c-5431c65d2c4f.png) 
![image](https://user-images.githubusercontent.com/39553613/85083161-cc9f9a80-b185-11ea-955a-57303709fae2.png)

### Also it seems not support for Petwer material(ingot)
![image](https://user-images.githubusercontent.com/39553613/85083366-6109fd00-b186-11ea-9397-d15b275965b4.png)
![image](https://user-images.githubusercontent.com/39553613/85083394-73843680-b186-11ea-8105-c595aa2199e1.png)

**Comment by Peatral** [comment] 2020-06-19 05:22
Oh this is interesting... I will definitely search the cause later.

**Comment by Peatral** [comment] 2020-06-19 11:18
The reason should be the same as in #4 actually, recipe registration doesn't work quite right if the fluid is called *_fluid or *fluid. Due to my long breaks in development I totally forgot that the bar stamping recipes etc. work via the fluid registry.

**Comment by Peatral** [comment] 2020-06-19 18:11
Fixed it with 190642dad27a8919d447bde537601f5dd304c7af.
This will be included when I make a new release next week (I don't like to make multiple releases per week because it can easily annoy people. Also this gives me the chance to fix more bugs etc. with one release aka put more stuff into a release). I hope it's okay for you to wait till wednesday or so. If it's a pressing issue I can give you a current build.

**Closed by Peatral** 2020-06-19 18:11 UTC
Labels: bug

**Comment by Caishangqi** [comment] 2020-06-19 20:04
> Fixed it with [190642d](https://github.com/Peatral/EmbersConstruct/commit/190642dad27a8919d447bde537601f5dd304c7af).
> This will be included when I make a new release next week (I don't like to make multiple releases per week because it can easily annoy people. Also this gives me the chance to fix more bugs etc. with one release aka put more stuff into a release). I hope it's okay for you to wait till wednesday or so. If it's a pressing issue I can give you a current build.

Thank you :)

**Comment by Peatral** [comment] 2020-06-24 08:24
Update 1.2.4 is now released: 0fbbf668e08bae56a12960215eb6fec59347e570
