### ISSUE TITLE
Crash on Launch?

### ISSUE THREAD

**Issue by Yourname942** [Peatral/EmbersConstruct#10] opened 2020-08-07 15:21 UTC
Does anyone know how to fix this error/ crash?

latest log: https://gist.github.com/Yourname942/2edaf002750d43d00cbea5e44bea47ae

crash log: https://gist.github.com/Yourname942/ca20cb4361224fb5f779fd517897bcae

Thank you.

**Comment by Peatral** [comment] 2020-08-07 15:25
This error should already be fixed in the newest version, also this is therefore a duplicate of #8.

**Closed by Peatral** 2020-08-07 15:25 UTC
Labels: duplicate
